#+Title: Academic writing
#+Date: 4th February 2020
#+setupfile: ../layouts/post.org

I plan to collect here resources on academic writing, style, preparing
talks and so on.


 * [[https://www.microsoft.com/en-us/research/academic-program/write-great-research-paper/#!other-resources][Write great research papers.]] Collection of links by Simon Peyton Jones.
 * [[https://www.microsoft.com/en-us/research/academic-program/how-to-write-a-great-research-proposal/][How to write a great research proposal.]] Simon Peyton Jones.
 * [[https://www.microsoft.com/en-us/research/academic-program/give-great-research-talk/][How to give a great research talk.]] Simon Peyton Jones.
 * [[https://www.math.uchicago.edu/~may/VIGRE/VIGRE2010/piiUJM2up.pdf][Writing a Math Phase Two Paper]]. Steven L. Kleiman.

* [[https://www.microsoft.com/en-us/research/academic-program/write-great-research-paper/][How to write a great research paper.]] /Simon Peyton Jones./
** 1. Don't wait, write.
Writing the paper forces you to do the necessary research and
understand what you want to say. Start writing before the research is
done. Apply lazy evaluation to the research.

 * This forces us to be clear and focused.
 * Highlights what we do not understand.
 * Opens the dialogue: you can start sharing with other people.
   You can even consider submitting work in progress to
   conferences.

Understand the writing not only as the output of research but as the
medium.

** 2. Convey a useful idea 
Make other people interested on your research; the ideas have to be
durable and catchy and get people excited about them. Ideas are
worthless if you keep them to yourself.

 * *Write about any idea.* You do not need to have a fantastic idea.
   We all feel that our ideas are insignificant.  Not much is loss if
   that is actually the case, but we can find things while trying to
   explain these ideas.  Get started, do not wait for ideas.

 * *The idea*. The paper needs to have one and only one /ping/: one
   clear, sharp idea. It needs to be clear when the paper is
   finished. If you have many ideas, write many different papers.

   * What is the key thought of any paper we read? We should make
     it clear to the authors.  You can even write a section called:
     /the main idea/ that makes it very explicit.

** 3. Tell a story.
Imagine a whiteboard explanation.

 * Here is a problem.
 * It is interesting.
 * However, it is unsolved.
 * Here is my idea.
 * And it works.
 * This is how it compares to other approaches.

A commmon structure for conference papers is the following.  You lose readers
as the paper advances, so you should carefully plan the first pages.

|----------------------+-------------+---------|
| Part                 | Length      | Readers |
|----------------------+-------------+---------|
| Title                | 1 sentence  |    1000 |
| Abstract             | 4 sentences |     100 |
| Introduction         | 1 page      |     100 |
| Problem              | 1 page      |      10 |
| Main idea            | 2 pages     |      10 |
| Details              | 5 pages     |       3 |
| Related work         | 1-2 pages   |      10 |
| Conclusions, further | 0.5 pages   |         |
|----------------------+-------------+---------|

** 4. The introduction
Describe the problem and state your contributions.
All of this is the first page, the one everyone will read.

 * How to introduce the problem? Use an /example/. Four lines and the
   first example should be there, to illustrate the problem.

 * Avoid a rant about how important is your problem. It seems good
   scholarship, but is demotivating to the reader. Simply put an
   example: "consider this thing, we will solve it in general".  It
   is better to describe a small goal, and then actually solve it.

 * *Contributions!* State the list of contributions first: bullet
   list. This is the specification of what your paper will do.  The
   reader should be excited about these contributions and then
   satisfied by the paper.

   * Contributions should be refutable, and with /forward/
     /references(!)/ to evidence.  You should point to where this is done in the
     paper in parentheses /"Exciting claim/ /(Section 3)"/ instead of
     saying /"Section 3/ /introduces..."/, which is utterly boring.

     |-------------------------------------------+-----|
     | We describe (system)                      | No  |
     | We give syntax and semantics for (system) | Yes |
     | We study its properties                   | No  |
     | We prove soundness and decidability       | Yes |
     | We use it in practice                     | No  |
     | We build a GUI for Java                   | Yes |
     |-------------------------------------------+-----|
        
     If something is not referred here, maybe it should not be on
     the paper.

 * *Related work* should not be on the introduction. It distracts
   your reader from the main idea. The reader knows nothing about
   the problem. It is better to move this to the end and do it
   comfortably, where the reader is familiarized with your terms.

   * There is a fallacy that says that to make your work look good,
     you have to make other people's work look bad.  Appreciation is
     a divisible commodity! do not do that.
        
        * Warmly acknowledge people who helped you.
        * Be generous to the competition /"In his inspiring paper..."/,
          /"The lucid work of..."/.
        * Express your gratitude to other papers.
        * Acknowledge weaknesses in your research; unawareness of the
          weaknesses is not helping. This goes at the end of the
          related work.

   * The related work should not be just a list of citations.

** 6. Put your readers first
Try not to recapitulate your journey; it was difficult for you to get
to this point, but the poor reader does not need to suffer that to
understand it was good.  The paper seems so simple that the reader
feels it is irrelevant? That does not mean you need to scare them. The
first approximation should not be scary.

 * Exception: explain what you did not do the obvious thing. Why are
   you not taking the obvious avenue?

 * It can be good to have an appendix for the painful details?

*Intuition.* The reader should be able to skip the details and still have
the intuition.

** 7. Listen to your readers
Get your paper read by as many friendly guinea pigs as possible. The
ideal would be some expert on the field that wants to read your paper;
but any other friendly advice is also useful.  Each guinea pig can read
your paper only one, so use them wisely.


